### ISSUE TITLE
cant use custom elements v1

### ISSUE THREAD

**Issue by janat08** [codemeasandwich/hyper-element#3]
In this example you include polyfill for v1, yet it refuses to work in my app, and breaks in the example:
https://jsfiddle.net/fwLbqmsj/

**Comment by janat08** [comment]
If I include the comprehensive polyfill it fails entirely: https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-lite.js

**Comment by janat08** [comment]
https://jsfiddle.net/fwLbqmsj/2/
Included the native bundle, does native es6 support exclude polyfills?

**Comment by codemeasandwich** [comment]
Your problem is in your resource links
1) webcomponentsjs: was linked to the github page. Not the source. 
Use -> https://cdn.jsdelivr.net/npm/webcomponentsjs@latest/lite.min.js
2) HyperHTML: you are missing the render lib
Use -> https://unpkg.com/hyperhtml@latest/min.js
3) hyper-element: the link is bad.
Use -> https://cdn.jsdelivr.net/npm/hyper-element@latest/source/hyperElement.js

Hope this help. 
Also star this project if you like :)
